export type ProductFolderGalleryManifest = Record<string, string[]>;

export const productFolderGalleryManifest: ProductFolderGalleryManifest = {
    "Women\u0027s Solid Color Halter Lace Sexy Bra And Panty Set":  [
                                                                        "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Solid_Color_Halter_Lace_Sexy_Bra_And_Panty_Set/17008956254cfda8afcbc659e4bcb1348649747124_thumbnail_600x.jpg",
                                                                        "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Solid_Color_Halter_Lace_Sexy_Bra_And_Panty_Set/17008956275ff2a210f1552eb1f5d20f6d6eba704f_thumbnail_600x.jpg",
                                                                        "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Solid_Color_Halter_Lace_Sexy_Bra_And_Panty_Set/1700895630a270824a03e08738b370f05825328e91_thumbnail_600x.jpg",
                                                                        "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Solid_Color_Halter_Lace_Sexy_Bra_And_Panty_Set/1700895634a6798d0bf84d774ad52ca38548aaef87_thumbnail_600x.jpg",
                                                                        "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Solid_Color_Halter_Lace_Sexy_Bra_And_Panty_Set/1700895638122a5291d5ecf59ba81b2264864b3ff5_thumbnail_600x.jpg"
                                                                    ],
    "Solid Color Hollow Out Mesh Bra And Triangle Underwear Sexy Lingerie Set, 2pcs. For Going Out":  [
                                                                                                          "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Solid_Color_Hollow_Out_Mesh_Bra_And_Triangle_Underwear_Sexy_Lingerie_Set_2pcs._For_Going_Out/17183471834525119197fbde4123ff4d5bb4ffc2b7_thumbnail_600x.jpg",
                                                                                                          "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Solid_Color_Hollow_Out_Mesh_Bra_And_Triangle_Underwear_Sexy_Lingerie_Set_2pcs._For_Going_Out/171834718544cf1673deb097c78a4d4b23a4a8b76e_thumbnail_600x.jpg",
                                                                                                          "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Solid_Color_Hollow_Out_Mesh_Bra_And_Triangle_Underwear_Sexy_Lingerie_Set_2pcs._For_Going_Out/17183471894d338f1425eb300a296c540d6b76321b_thumbnail_600x.jpg",
                                                                                                          "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Solid_Color_Hollow_Out_Mesh_Bra_And_Triangle_Underwear_Sexy_Lingerie_Set_2pcs._For_Going_Out/1718347198c3082cf17aa6eaed115598f2eb1d80e0_thumbnail_600x.jpg",
                                                                                                          "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Solid_Color_Hollow_Out_Mesh_Bra_And_Triangle_Underwear_Sexy_Lingerie_Set_2pcs._For_Going_Out/1718347204772ccfc2a129b50c83009d622c257d3c_thumbnail_600x.jpg"
                                                                                                      ],
    "Floral Underwire Puff Sleeve Lace Patchwork Top + Thong + Skirt 3pcs Set Bridal Lingerie Set, Going Out":  [
                                                                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Floral_Underwire_Puff_Sleeve_Lace_Patchwork_Top_Thong_Skirt_3pcs_Set_Bridal_Lingerie_Set_Going_Out/17200713865ac2497ceedd0dd6e15d95e15ea798a9_thumbnail_600x.jpg",
                                                                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Floral_Underwire_Puff_Sleeve_Lace_Patchwork_Top_Thong_Skirt_3pcs_Set_Bridal_Lingerie_Set_Going_Out/1720071391d8df91aed2a448873d0dcf95c15bc09c_thumbnail_600x.jpg",
                                                                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Floral_Underwire_Puff_Sleeve_Lace_Patchwork_Top_Thong_Skirt_3pcs_Set_Bridal_Lingerie_Set_Going_Out/1720071394af3a439d54ccb0ad3279affd1ec1d73d_thumbnail_600x.jpg",
                                                                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Floral_Underwire_Puff_Sleeve_Lace_Patchwork_Top_Thong_Skirt_3pcs_Set_Bridal_Lingerie_Set_Going_Out/1720071398551c114ec9ae87552596d689b3df010c_thumbnail_600x_1_.jpg",
                                                                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Floral_Underwire_Puff_Sleeve_Lace_Patchwork_Top_Thong_Skirt_3pcs_Set_Bridal_Lingerie_Set_Going_Out/1720071398551c114ec9ae87552596d689b3df010c_thumbnail_600x.jpg"
                                                                                                                ],
    "Seduluxe 1pc Lace Front Closure Wireless Bra For Women":  [
                                                                   "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Seduluxe_1pc_Lace_Front_Closure_Wireless_Bra_For_Women/17665634013ea16b4f7e41bd4b5453a812e2821723_thumbnail_600x.jpg",
                                                                   "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Seduluxe_1pc_Lace_Front_Closure_Wireless_Bra_For_Women/176656340367178cdd5e4de182b990c94c0a8adc31_thumbnail_600x.jpg",
                                                                   "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Seduluxe_1pc_Lace_Front_Closure_Wireless_Bra_For_Women/1766563405ce16c711c74f22615da474d37a6b31a9_thumbnail_600x.jpg",
                                                                   "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Seduluxe_1pc_Lace_Front_Closure_Wireless_Bra_For_Women/1766563406d587d57fcb1de01e01f49d94f566a77a_thumbnail_600x.jpg",
                                                                   "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Seduluxe_1pc_Lace_Front_Closure_Wireless_Bra_For_Women/176656340755eb9a9409e95abb78281b9bd9a50b4e_thumbnail_600x.jpg",
                                                                   "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Seduluxe_1pc_Lace_Front_Closure_Wireless_Bra_For_Women/1766563409873c4bce239f4df38ed47a4e544b42cc_thumbnail_600x.jpg"
                                                               ],
    "Ladies\u0027 Sexy Pu Leather Backless Halter Neck Lingerie Dress":  [
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Ladies_Sexy_Pu_Leather_Backless_Halter_Neck_Lingerie_Dress/1733913680dd2435df435fdf12e33eb3bbd6dd44b9_thumbnail_600x.jpg",
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Ladies_Sexy_Pu_Leather_Backless_Halter_Neck_Lingerie_Dress/17339136837ca5fbe3c2b50e13c83298b5cebef674_thumbnail_600x.jpg",
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Ladies_Sexy_Pu_Leather_Backless_Halter_Neck_Lingerie_Dress/1733913685507f15487d87a4c738b6cc04d0f0331f_thumbnail_600x.jpg",
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Ladies_Sexy_Pu_Leather_Backless_Halter_Neck_Lingerie_Dress/17339136885d624c708599875ca0942d3bbd8a675c_thumbnail_600x.jpg",
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Ladies_Sexy_Pu_Leather_Backless_Halter_Neck_Lingerie_Dress/17339136912358a6bb7f155f6cacc5ff7df9580719_thumbnail_600x.jpg",
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Ladies_Sexy_Pu_Leather_Backless_Halter_Neck_Lingerie_Dress/17339136947d62b248c1daebd70c4917d698a76f90_thumbnail_600x.jpg"
                                                                         ],
    "1 Set Women\u0027s Sexy Lingerie, Black Sheer Backless Bodysuit + Garter Stockings + Pantyhose, Heart Pattern Design, No Need To Remove, Convenient For Play, Hollow-Out Design, Seductive, Full Of Love, Ideal For Valentine\u0027s Day":  [
                                                                                                                                                                                                                                                     "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/1_Set_Women_s_Sexy_Lingerie_Black_Sheer_Backless_Bodysuit_Garter_Stockings_Pantyhose_Heart_Pattern_Design_No_Need_To_Remove_Convenient_For_Play_Hollow-Out_Design_Seductive_Full_Of_Love_Ideal_For_Valentine_s_Day/1746022225321e3a921929caf887c4d4ec193805e2_thumbnail_600x.jpg",
                                                                                                                                                                                                                                                     "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/1_Set_Women_s_Sexy_Lingerie_Black_Sheer_Backless_Bodysuit_Garter_Stockings_Pantyhose_Heart_Pattern_Design_No_Need_To_Remove_Convenient_For_Play_Hollow-Out_Design_Seductive_Full_Of_Love_Ideal_For_Valentine_s_Day/1746022234421ff7171e2ae4669a743e4454585d49_thumbnail_600x_1_.jpg",
                                                                                                                                                                                                                                                     "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/1_Set_Women_s_Sexy_Lingerie_Black_Sheer_Backless_Bodysuit_Garter_Stockings_Pantyhose_Heart_Pattern_Design_No_Need_To_Remove_Convenient_For_Play_Hollow-Out_Design_Seductive_Full_Of_Love_Ideal_For_Valentine_s_Day/174602224613b63e0c147afb0cf54ecd6e75451e96_thumbnail_600x_2_.jpg",
                                                                                                                                                                                                                                                     "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/1_Set_Women_s_Sexy_Lingerie_Black_Sheer_Backless_Bodysuit_Garter_Stockings_Pantyhose_Heart_Pattern_Design_No_Need_To_Remove_Convenient_For_Play_Hollow-Out_Design_Seductive_Full_Of_Love_Ideal_For_Valentine_s_Day/1746022251b3121380538fe9187cab51f9a5ece1fa_thumbnail_600x.jpg"
                                                                                                                                                                                                                                                 ],
    "4pcs Women\u0027s Punk Style Choker With Spaghetti Strap Garter Belt \u0026 Leg Ring And Sexy Ruffle Dress Set Lingerie":  [
                                                                                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/4pcs_Women_s_Punk_Style_Choker_With_Spaghetti_Strap_Garter_Belt_Leg_Ring_And_Sexy_Ruffle_Dress_Set_Lingerie/171806864869c8f8a5884cac96640e41d515763e15_thumbnail_600x.jpg",
                                                                                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/4pcs_Women_s_Punk_Style_Choker_With_Spaghetti_Strap_Garter_Belt_Leg_Ring_And_Sexy_Ruffle_Dress_Set_Lingerie/1718068651b8a72749086d8714be13f609b9882e14_thumbnail_600x.jpg",
                                                                                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/4pcs_Women_s_Punk_Style_Choker_With_Spaghetti_Strap_Garter_Belt_Leg_Ring_And_Sexy_Ruffle_Dress_Set_Lingerie/1718068655e6c3e4f103e0c1a640ccce8b11dfcd9b_thumbnail_600x_1_.jpg",
                                                                                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/4pcs_Women_s_Punk_Style_Choker_With_Spaghetti_Strap_Garter_Belt_Leg_Ring_And_Sexy_Ruffle_Dress_Set_Lingerie/1718068655e6c3e4f103e0c1a640ccce8b11dfcd9b_thumbnail_600x_2_.jpg",
                                                                                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/4pcs_Women_s_Punk_Style_Choker_With_Spaghetti_Strap_Garter_Belt_Leg_Ring_And_Sexy_Ruffle_Dress_Set_Lingerie/1718068655e6c3e4f103e0c1a640ccce8b11dfcd9b_thumbnail_600x.jpg"
                                                                                                                                ],
    "2pcs Women\u0027s Sexy Lingerie Set, Lace \u0026 Satin Splice Sexy Club Outfit, Suitable For Home, Holiday, Party, Romantic Occasions":  [
                                                                                                                                                  "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/2pcs_Women_s_Sexy_Lingerie_Set_Lace_Satin_Splice_Sexy_Club_Outfit_Suitable_For_Home_Holiday_Party_Romantic_Occasions/1749515992f90a09684a2558430f3c4ce6906325ae_thumbnail_600x.jpg",
                                                                                                                                                  "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/2pcs_Women_s_Sexy_Lingerie_Set_Lace_Satin_Splice_Sexy_Club_Outfit_Suitable_For_Home_Holiday_Party_Romantic_Occasions/17499540230d77b06430a376e5931285dcc4040d5a_thumbnail_600x.jpg",
                                                                                                                                                  "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/2pcs_Women_s_Sexy_Lingerie_Set_Lace_Satin_Splice_Sexy_Club_Outfit_Suitable_For_Home_Holiday_Party_Romantic_Occasions/17499540230d9bd578ae19684bc5530252a2fb48c7_thumbnail_600x.jpg",
                                                                                                                                                  "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/2pcs_Women_s_Sexy_Lingerie_Set_Lace_Satin_Splice_Sexy_Club_Outfit_Suitable_For_Home_Holiday_Party_Romantic_Occasions/1749954024986f92629e07b6362c7a44e4dea0674e_thumbnail_600x.jpg"
                                                                                                                                              ],
    "Sleeveless Sexy Bandage Dress - Elegant Black \u0026 White Round Neck Long Fitted Design - Slit Hem, Tie Detail, Suitable For Summer Party \u0026 Evening Wear":  [
                                                                                                                                                                           "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Sleeveless_Sexy_Bandage_Dress_-_Elegant_Black_White_Round_Neck_Long_Fitted_Design_-_Slit_Hem_Tie_Detail_Suitable_For_Summer_Party_Evening_Wear/1740214819109aa8bb843d14d0635e1cdfd731200c_thumbnail_600x.jpg",
                                                                                                                                                                           "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Sleeveless_Sexy_Bandage_Dress_-_Elegant_Black_White_Round_Neck_Long_Fitted_Design_-_Slit_Hem_Tie_Detail_Suitable_For_Summer_Party_Evening_Wear/1740214829c55a69604848a81ed1bfc0618c85aa61_thumbnail_600x.jpg",
                                                                                                                                                                           "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Sleeveless_Sexy_Bandage_Dress_-_Elegant_Black_White_Round_Neck_Long_Fitted_Design_-_Slit_Hem_Tie_Detail_Suitable_For_Summer_Party_Evening_Wear/1740214841c8141b4ec934a07eced801ff88a67643_thumbnail_600x.jpg",
                                                                                                                                                                           "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Sleeveless_Sexy_Bandage_Dress_-_Elegant_Black_White_Round_Neck_Long_Fitted_Design_-_Slit_Hem_Tie_Detail_Suitable_For_Summer_Party_Evening_Wear/174021486114616405ee99ab2b91fa98dda21271f7_thumbnail_600x.jpg",
                                                                                                                                                                           "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Sleeveless_Sexy_Bandage_Dress_-_Elegant_Black_White_Round_Neck_Long_Fitted_Design_-_Slit_Hem_Tie_Detail_Suitable_For_Summer_Party_Evening_Wear/174021487402470beec57da278f61c5d465d0a805a_thumbnail_600x.jpg",
                                                                                                                                                                           "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Sleeveless_Sexy_Bandage_Dress_-_Elegant_Black_White_Round_Neck_Long_Fitted_Design_-_Slit_Hem_Tie_Detail_Suitable_For_Summer_Party_Evening_Wear/1740214878252f95e7e84c0dcd74987c2bb0af2556_thumbnail_600x.jpg"
                                                                                                                                                                       ],
    "Hollow Out Leopard Print Wrap-Around Sexy Lingerie For Going Out":  [
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Hollow_Out_Leopard_Print_Wrap-Around_Sexy_Lingerie_For_Going_Out/172135882235d10006bbb27007f4fd4e5a03da08b9_thumbnail_600x.jpg",
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Hollow_Out_Leopard_Print_Wrap-Around_Sexy_Lingerie_For_Going_Out/1721358826f062c608415bf914b555560f010c2355_thumbnail_600x.jpg",
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Hollow_Out_Leopard_Print_Wrap-Around_Sexy_Lingerie_For_Going_Out/1721358829bfbf9afc4676be2856787486e3ac22cf_thumbnail_600x.jpg",
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Hollow_Out_Leopard_Print_Wrap-Around_Sexy_Lingerie_For_Going_Out/1721358831f8549bdc57fc9988b7772bc91297047f_thumbnail_600x.jpg",
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Hollow_Out_Leopard_Print_Wrap-Around_Sexy_Lingerie_For_Going_Out/17213588355f6d1f23368a15197a791c9011d0d9a1_thumbnail_600x.jpg",
                                                                             "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Hollow_Out_Leopard_Print_Wrap-Around_Sexy_Lingerie_For_Going_Out/172135883786ae9d99979a9b8cfe07ab2b0d3eff26_thumbnail_600x.jpg"
                                                                         ],
    "1PC Women Sexy Lingerie Bodysuit Sexy Fishnet Cover Up Without Bikini For Music Festival Hollow Out Bodycon Dress See Through Beachwear Summer Women\u0027s Swimwear Clothing Swimsuit":  [
                                                                                                                                                                                                   "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/1PC_Women_Sexy_Lingerie_Bodysuit_Sexy_Fishnet_Cover_Up_Without_Bikini_For_Music_Festival_Hollow_Out_Bodycon_Dress_See_Through_Beachwear_Summer_Women_s_Swimwear_Clothing_Swimsuit/17473763427c366c313e2b41b2c3a7fb6c654004b7_thumbnail_600x.jpg",
                                                                                                                                                                                                   "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/1PC_Women_Sexy_Lingerie_Bodysuit_Sexy_Fishnet_Cover_Up_Without_Bikini_For_Music_Festival_Hollow_Out_Bodycon_Dress_See_Through_Beachwear_Summer_Women_s_Swimwear_Clothing_Swimsuit/1747376344ad3a62eac4085d6b93db081a82f1db8a_thumbnail_600x.jpg",
                                                                                                                                                                                                   "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/1PC_Women_Sexy_Lingerie_Bodysuit_Sexy_Fishnet_Cover_Up_Without_Bikini_For_Music_Festival_Hollow_Out_Bodycon_Dress_See_Through_Beachwear_Summer_Women_s_Swimwear_Clothing_Swimsuit/1747376344dcc258698de14f2a1fa52bf34ef47603_thumbnail_600x.jpg"
                                                                                                                                                                                               ],
    "Women\u0027s Fashionable Tie Dye Slim Flared Long Pants":  [
                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Fashionable_Tie_Dye_Slim_Flared_Long_Pants/17114260010f674ff4cd464a34df19efdabc46a7e8_thumbnail_600x.jpg",
                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Fashionable_Tie_Dye_Slim_Flared_Long_Pants/17114260062459f171666d7676805e53113656dad0_thumbnail_600x.jpg",
                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Fashionable_Tie_Dye_Slim_Flared_Long_Pants/1711426010683f080ed96700a4567ab90dad699769_thumbnail_600x.jpg",
                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Fashionable_Tie_Dye_Slim_Flared_Long_Pants/1711426014415d4b043fb8b8bd2f3aa18a9b479d3c_thumbnail_600x_1_.jpg",
                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Fashionable_Tie_Dye_Slim_Flared_Long_Pants/1711426014415d4b043fb8b8bd2f3aa18a9b479d3c_thumbnail_600x.jpg",
                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Fashionable_Tie_Dye_Slim_Flared_Long_Pants/17114260188532e2732eaab915208377d6014324bf_thumbnail_600x.jpg",
                                                                    "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/Women_s_Fashionable_Tie_Dye_Slim_Flared_Long_Pants/17114260220478a6d2c694293d312badb8b30f622a_thumbnail_600x.jpg"
                                                                ],
    "3pcs Women\u0027s Black Sexy Patent Leather Metallic Strap Halloween Costume Mesh Slit Maxi Dress Lingerie Set, Suitable For Home, Private Party Or Nightclub Wear, Sexy Lingerie":  [
                                                                                                                                                                                              "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Women_s_Black_Sexy_Patent_Leather_Metallic_Strap_Halloween_Costume_Mesh_Slit_Maxi_Dress_Lingerie_Set_Suitable_For_Home_Private_Party_Or_Nightclub_Wear_Sexy_Lingerie/175394207917e55770b830b744c9600e556222f67e_thumbnail_600x.jpg",
                                                                                                                                                                                              "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Women_s_Black_Sexy_Patent_Leather_Metallic_Strap_Halloween_Costume_Mesh_Slit_Maxi_Dress_Lingerie_Set_Suitable_For_Home_Private_Party_Or_Nightclub_Wear_Sexy_Lingerie/1753942079bdcb1f0a8a20a9835ced82477bda9d9b_thumbnail_600x.jpg",
                                                                                                                                                                                              "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Women_s_Black_Sexy_Patent_Leather_Metallic_Strap_Halloween_Costume_Mesh_Slit_Maxi_Dress_Lingerie_Set_Suitable_For_Home_Private_Party_Or_Nightclub_Wear_Sexy_Lingerie/1753942080284c06570e849e986a5d3df31c30d12c_thumbnail_600x.jpg",
                                                                                                                                                                                              "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Women_s_Black_Sexy_Patent_Leather_Metallic_Strap_Halloween_Costume_Mesh_Slit_Maxi_Dress_Lingerie_Set_Suitable_For_Home_Private_Party_Or_Nightclub_Wear_Sexy_Lingerie/1753942080e0b7024363d8a638c5ef45c8822ae557_thumbnail_600x.jpg",
                                                                                                                                                                                              "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Women_s_Black_Sexy_Patent_Leather_Metallic_Strap_Halloween_Costume_Mesh_Slit_Maxi_Dress_Lingerie_Set_Suitable_For_Home_Private_Party_Or_Nightclub_Wear_Sexy_Lingerie/1753942204db8fe7bf8da9693e4d9392775fa5969c_thumbnail_600x.jpg"
                                                                                                                                                                                          ],
    "3pcs Sexy Lingerie Set For Women (With Underwire Bra, G-String, And Mini Skirt)":  [
                                                                                            "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Sexy_Lingerie_Set_For_Women_With_Underwire_Bra_G-String_And_Mini_Skirt/17674949420ceba769f5d12919145a03aaf886f17f_thumbnail_600x.jpg",
                                                                                            "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Sexy_Lingerie_Set_For_Women_With_Underwire_Bra_G-String_And_Mini_Skirt/1767494943a782b4d59644b4bd8ef28694a2cbe528_thumbnail_600x.jpg",
                                                                                            "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Sexy_Lingerie_Set_For_Women_With_Underwire_Bra_G-String_And_Mini_Skirt/1767494945506ef9fdd29025d0ef47c1e2c4daa3cc_thumbnail_600x.jpg",
                                                                                            "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Sexy_Lingerie_Set_For_Women_With_Underwire_Bra_G-String_And_Mini_Skirt/1767494946f5dfc2b4f529a9df57d526d80cd5b877_thumbnail_600x.jpg",
                                                                                            "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Sexy_Lingerie_Set_For_Women_With_Underwire_Bra_G-String_And_Mini_Skirt/17674949474776ec388dfdb6824733c94c0bad3393_thumbnail_600x.jpg",
                                                                                            "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Sexy_Lingerie_Set_For_Women_With_Underwire_Bra_G-String_And_Mini_Skirt/17674949499d8e61f3b80ff16cd94abffb7ff093ee_thumbnail_600x_1_.jpg",
                                                                                            "https://yqhcbasmpotpgxybfjzo.supabase.co/storage/v1/object/public/product-images/3pcs_Sexy_Lingerie_Set_For_Women_With_Underwire_Bra_G-String_And_Mini_Skirt/17674949499d8e61f3b80ff16cd94abffb7ff093ee_thumbnail_600x.jpg"
                                                                                        ]
} as const;

