export type ProductVariantManifest = Record<string, Record<string, string[]>>;

export const productVariantManifest: ProductVariantManifest = {
    "EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look":  {
                                                                                                                                                                  "red":  [
                                                                                                                                                                              "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/red/1770953515276b01042d1b6222520292e66f5c4dfa_thumbnail_600x.jpg",
                                                                                                                                                                              "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/red/17709535172825c43b3eb6dc6a33ea71b23bf37457_thumbnail_600x.jpg",
                                                                                                                                                                              "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/red/17709535180297b9a9323485f69109ed32d936c96b_thumbnail_600x.jpg",
                                                                                                                                                                              "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/red/1770953520afe795ce90fe63b5c6183bb42006d25b_thumbnail_600x.jpg",
                                                                                                                                                                              "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/red/1770953521f0c23042bfcf26f36340b3f3cc2c20c1_thumbnail_600x.jpg",
                                                                                                                                                                              "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/red/1770953523313813a89a10e3ec10e4475aa96eca30_thumbnail_600x.jpg",
                                                                                                                                                                              "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/red/17709535240af4fefe0a1cfe251798dbc018609086_thumbnail_600x.jpg"
                                                                                                                                                                          ],
                                                                                                                                                                  "white":  [
                                                                                                                                                                                "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/white/171193453954d4ffedbd3dcdade51da8c360e04072_thumbnail_600x.jpg",
                                                                                                                                                                                "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/white/1711934542bd71bc051a87b88a2befc3bb96e36204_thumbnail_600x.jpg",
                                                                                                                                                                                "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/white/1711934546b7b11dd59a6f5e44b793f871076c7cda_thumbnail_600x.jpg",
                                                                                                                                                                                "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/white/17119345486b640aff54fee1b5de80175a5a87bbec_thumbnail_600x.jpg",
                                                                                                                                                                                "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/white/1711934552df5334c7d75f78a36d59efd36968e45c_thumbnail_600x.jpg"
                                                                                                                                                                            ],
                                                                                                                                                                  "black":  [
                                                                                                                                                                                "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/black/1772607749b43cdb6d086c5696a54df4ecae69474a_thumbnail_600x.jpg",
                                                                                                                                                                                "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/black/177260775185e05f850d2bb9bd548e100395cfe1db_thumbnail_600x.jpg",
                                                                                                                                                                                "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/black/17726077524fdb71ca78e902b91789d2bdeb155eca_thumbnail_600x.jpg",
                                                                                                                                                                                "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/black/1772607753e0a795c5bf9088a082c1b52af650e41a_thumbnail_600x.jpg",
                                                                                                                                                                                "/EmpressEnvy Women\u0027s Classic Sexy Black Lace Semi Sheer Babydoll With Cut Out Details And Spaghetti Strap, Short Length Lingerie Set, Baddie Look/black/1772607755785f5b1a3e41768fb21135ddb0c31535_thumbnail_600x.jpg"
                                                                                                                                                                            ]
                                                                                                                                                              },
    "Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress":  {
                                                                                                  "white":  [
                                                                                                                "/Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress/white/17327702212c9930921adfeea2123f679e121658a9_thumbnail_600x.jpg",
                                                                                                                "/Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress/white/17327702213337c666ba9690702ee6f7c669cf46cd_thumbnail_600x.jpg",
                                                                                                                "/Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress/white/17327702221c74df076ee0dbc66075fd26b4b6db98_thumbnail_600x.jpg",
                                                                                                                "/Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress/white/173277022249aa0f9c1c949cf796fd98d62d08d881_thumbnail_600x.jpg",
                                                                                                                "/Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress/white/17327702227e06893d4ea8cec2b6461d803b742573_thumbnail_600x.jpg",
                                                                                                                "/Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress/white/1732770222addb082fbee62c129e19f3b0c5524962_thumbnail_600x.jpg"
                                                                                                            ],
                                                                                                  "black":  [
                                                                                                                "/Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress/black/172319711197d8b2c0bee3cb51cc4b46ad769849ef_thumbnail_600x.jpg",
                                                                                                                "/Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress/black/1723197112024dc0e3f9a4c0ed6b71b59e921a5a6a_thumbnail_600x.jpg",
                                                                                                                "/Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress/black/17231971123e6ecbb052b88c8f48dcbbcde43fa57c_thumbnail_600x.jpg",
                                                                                                                "/Plus Size Lingerie, Hollow Out Cover-Up, Sheer Solid Color High Elasticity Lace Dress/black/1723197112ae65fddce67262f205abde0e05b871b2_thumbnail_600x.jpg"
                                                                                                            ]
                                                                                              },
    "Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie":  {
                                                                                   "burgundy":  [
                                                                                                    "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/burgundy/1713164654ac904817b983fc04a807e29ea296ca75_thumbnail_600x.jpg",
                                                                                                    "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/burgundy/17131646647b6706e5965be6071ab3676a82efd2e3_thumbnail_600x.jpg"
                                                                                                ],
                                                                                   "blue":  [
                                                                                                "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/blue/17061784551126ff50ad496f1ee1409abfd8b909e7_thumbnail_600x.jpg",
                                                                                                "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/blue/170617846062be79f62843cbe2b64f6dcdf3d9ff22_thumbnail_600x.jpg",
                                                                                                "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/blue/17061784655d5f8083a15980c1fa3c37a9b662046f_thumbnail_600x.jpg",
                                                                                                "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/blue/170617847029f70deab1c9f51ce510a08f6a07c954_thumbnail_600x.jpg"
                                                                                            ],
                                                                                   "white":  [
                                                                                                 "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/white/16981246925c798d7932c5654d1422d08d537bf573_thumbnail_600x.jpg",
                                                                                                 "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/white/1698124696a2265f7865d89615df55add9e701faf5_thumbnail_600x.jpg",
                                                                                                 "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/white/1698124701830b509049d7ee119b4c8d96b7d39a22_thumbnail_600x.jpg",
                                                                                                 "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/white/16981247057b4187272daf1927cd4e7cc1b6379029_thumbnail_600x.jpg"
                                                                                             ],
                                                                                   "pink":  [
                                                                                                "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/pink/1706178454809ec134b21803e3ad6a4e80e5bc7851_thumbnail_600x.jpg",
                                                                                                "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/pink/17061784601e54e83d2aa49b2ad40549fac913d4ea_thumbnail_600x.jpg"
                                                                                            ],
                                                                                   "black":  [
                                                                                                 "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/black/1703813861e16c7eb32332f898e2e429b76ebebe7b_thumbnail_600x.jpg",
                                                                                                 "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/black/1703813865d52aa98a061873be1ec6af4995cb14a3_thumbnail_600x.jpg",
                                                                                                 "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/black/1703813867eaacea6a9640e4998743ebbafc2655ec_thumbnail_600x.jpg",
                                                                                                 "/Crystal Vow Hollow Out Scallop Trim Lace Panty Lingerie Bridallingerie/black/1703813871e998c7ba358bcc18025be5c2f254ac52_thumbnail_600x.jpg"
                                                                                             ]
                                                                               },
    "ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,":  {
                                                                                                                                       "pink":  [
                                                                                                                                                    "/ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,/pink/1721793788d25c614aeb6fd761c38481c27605aabb_thumbnail_600x.jpg",
                                                                                                                                                    "/ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,/pink/1721793792d58ab96c1de49281824266c5a5ddfc3c_thumbnail_600x.jpg",
                                                                                                                                                    "/ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,/pink/172179379546c8da322b3e01901974f6890cf32148_thumbnail_600x.jpg",
                                                                                                                                                    "/ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,/pink/1721793799eefe6d50eb05828f2bb69fab36c0f3af_thumbnail_600x.jpg",
                                                                                                                                                    "/ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,/pink/172179380359edb8b15db753b08d7edd22da52fe0c_thumbnail_600x.jpg"
                                                                                                                                                ],
                                                                                                                                       "black":  [
                                                                                                                                                     "/ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,/black/17418625425253c235d0e4b40efad744effd139943_thumbnail_600x.jpg",
                                                                                                                                                     "/ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,/black/1741862546befc94c5caa5dbf0d633563b4b12ca3a_thumbnail_600x.jpg",
                                                                                                                                                     "/ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,/black/17418625494e5f5da52aa50ecdd851e8980fac19a0_thumbnail_600x.jpg",
                                                                                                                                                     "/ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,/black/17418626045aad7b78302b3caa017b0976d3631f4a_thumbnail_600x.jpg",
                                                                                                                                                     "/ChaseTheNight 2pcs Women Sexy Mesh Lingerie Set For Going Out, Lingerie For Women,Sexy,Valentine\u0027s Day,Sexy Lingerie,/black/17418626084840210fc4d80c9799dfc4f31d15e8da_thumbnail_600x.jpg"
                                                                                                                                                 ]
                                                                                                                                   },
    "2pcs Set Dark Aesthetic Sexy Lingerie Set, 3pcs Women Lace Bra And Panty Set With Underwire And No Padding, Suitable For Outerwear, Create A Bad Girl Look":  {
                                                                                                                                                                       "RED":  [
                                                                                                                                                                                   "/2pcs Set Dark Aesthetic Sexy Lingerie Set, 3pcs Women Lace Bra And Panty Set With Underwire And No Padding, Suitable For Outerwear, Create A Bad Girl Look/RED/17488306802bd62bce89a8e3b8dc1bed55e39dbb7d_thumbnail_600x.jpg",
                                                                                                                                                                                   "/2pcs Set Dark Aesthetic Sexy Lingerie Set, 3pcs Women Lace Bra And Panty Set With Underwire And No Padding, Suitable For Outerwear, Create A Bad Girl Look/RED/17488306807696cb88d4faf253c8356962b24e5997_thumbnail_600x.jpg",
                                                                                                                                                                                   "/2pcs Set Dark Aesthetic Sexy Lingerie Set, 3pcs Women Lace Bra And Panty Set With Underwire And No Padding, Suitable For Outerwear, Create A Bad Girl Look/RED/17488306808594f36882e4c1d85cc5b4cbaeb58e0b_thumbnail_600x.jpg",
                                                                                                                                                                                   "/2pcs Set Dark Aesthetic Sexy Lingerie Set, 3pcs Women Lace Bra And Panty Set With Underwire And No Padding, Suitable For Outerwear, Create A Bad Girl Look/RED/174883068087e903880790c95cb1b4bfbfd0f46c87_thumbnail_600x.jpg",
                                                                                                                                                                                   "/2pcs Set Dark Aesthetic Sexy Lingerie Set, 3pcs Women Lace Bra And Panty Set With Underwire And No Padding, Suitable For Outerwear, Create A Bad Girl Look/RED/1748830680bf9dd265d5c61ffc35e1148d7001defe_thumbnail_600x.jpg"
                                                                                                                                                                               ],
                                                                                                                                                                       "BLACK":  [
                                                                                                                                                                                     "/2pcs Set Dark Aesthetic Sexy Lingerie Set, 3pcs Women Lace Bra And Panty Set With Underwire And No Padding, Suitable For Outerwear, Create A Bad Girl Look/BLACK/17563681270439f097dcfeb878a6769bc9eab21392_thumbnail_600x.jpg",
                                                                                                                                                                                     "/2pcs Set Dark Aesthetic Sexy Lingerie Set, 3pcs Women Lace Bra And Panty Set With Underwire And No Padding, Suitable For Outerwear, Create A Bad Girl Look/BLACK/17563681303e86f28409c2eac74d2c5fbb28ab0d8e_thumbnail_600x.jpg",
                                                                                                                                                                                     "/2pcs Set Dark Aesthetic Sexy Lingerie Set, 3pcs Women Lace Bra And Panty Set With Underwire And No Padding, Suitable For Outerwear, Create A Bad Girl Look/BLACK/1756368136474cc049febd1de57310a6f4b7c437ff_thumbnail_600x.jpg",
                                                                                                                                                                                     "/2pcs Set Dark Aesthetic Sexy Lingerie Set, 3pcs Women Lace Bra And Panty Set With Underwire And No Padding, Suitable For Outerwear, Create A Bad Girl Look/BLACK/1756368148c6bf6b672686b7522430ac3ce3c2220f_thumbnail_600x.jpg"
                                                                                                                                                                                 ]
                                                                                                                                                                   },
    "4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set":  {
                                                                          "burgundy":  [
                                                                                           "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/burgundy/1756775175c561158d84d62fe290432a1773dc1e34_thumbnail_600x.jpg",
                                                                                           "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/burgundy/1756775177f4510e69b3b5311574e604f0a509a793_thumbnail_600x (1).jpg",
                                                                                           "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/burgundy/1756775177f4510e69b3b5311574e604f0a509a793_thumbnail_600x.jpg",
                                                                                           "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/burgundy/1756775181cb4204fe27b335ea6057b4a47ee04715_thumbnail_600x.jpg"
                                                                                       ],
                                                                          "blue":  [
                                                                                       "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/blue/17495198144439bb65f03042245ecedbed9cfc50dc_thumbnail_600x.jpg",
                                                                                       "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/blue/174951981706d755926be26720ae43e914f3faa09d_thumbnail_600x.jpg",
                                                                                       "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/blue/1749519818bce6e7093e287acff8784d5900ec8d80_thumbnail_600x.jpg",
                                                                                       "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/blue/1749519820a30d2c0adc180bdb39bfcf61e75587ae_thumbnail_600x.jpg",
                                                                                       "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/blue/174951982153b4ba8469c8afc037f8daa0e9def135_thumbnail_600x.jpg"
                                                                                   ],
                                                                          "white":  [
                                                                                        "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/white/1741161049a2a120d409fd56a501714a31f6b6fcc7_thumbnail_600x.jpg",
                                                                                        "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/white/17411610528792649b5b9d6bc8fbd6cac63ff44874_thumbnail_600x.jpg",
                                                                                        "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/white/17411610559a668b7987386a900f64a186f322a603_thumbnail_600x.jpg",
                                                                                        "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/white/17411610585163a3d0c8503220714108a933fbd45a_thumbnail_600x.jpg",
                                                                                        "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/white/1741161062d75e0a6b72e5e1bf6373cfd5083d86e5_thumbnail_600x.jpg"
                                                                                    ],
                                                                          "pink":  [
                                                                                       "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/pink/17089109381fbbe6f090b759dd2d7e3a1218e4d550_thumbnail_600x.jpg",
                                                                                       "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/pink/1708910941dfbfb2515f7ba7493671968c6cfc75db_thumbnail_600x.jpg",
                                                                                       "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/pink/1708910945e9ddeece213427c2b6ebaa6383616b09_thumbnail_600x.jpg",
                                                                                       "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/pink/1708910947d9e7648f939f03d419a6608461f2e5ba_thumbnail_600x.jpg",
                                                                                       "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/pink/17089109514d8ff82a1aff21890880e4562f720b2e_thumbnail_600x.jpg"
                                                                                   ],
                                                                          "black":  [
                                                                                        "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/black/172871697512cbf3ccaaaeca9aa85fd76df226d34d_thumbnail_600x.jpg",
                                                                                        "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/black/17350286554c6001192e26d09f4c89a075245a4f15_thumbnail_600x.jpg",
                                                                                        "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/black/17350286581a895f2678afd12d8994420a63145a9b_thumbnail_600x.jpg",
                                                                                        "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/black/1735028661867a9a792577cceb078005bc6128eed8_thumbnail_600x.jpg",
                                                                                        "/4pcs Mature Series Lace Patchwork Underwire Bodycon Dress Set/black/1735028664c5e0ee337a290fd9355aa3ad72919ae4_thumbnail_600x.jpg"
                                                                                    ]
                                                                      },
    "3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ":  {
                                                                                                                                                                                                                            "RED":  [
                                                                                                                                                                                                                                        "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/RED/17738182628c0f17fd4a9ee8a75267c7dcadc8aa28_thumbnail_600x.jpg",
                                                                                                                                                                                                                                        "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/RED/1773818264b2269524bba723d7e8b51ad7ff037fa1_thumbnail_600x (1).jpg",
                                                                                                                                                                                                                                        "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/RED/1773818265fee17db08426ff86f72b771486263db7_thumbnail_600x.jpg",
                                                                                                                                                                                                                                        "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/RED/17738182663cd0e62f70b7f31941458421cca92b11_thumbnail_600x (1).jpg",
                                                                                                                                                                                                                                        "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/RED/17738182663cd0e62f70b7f31941458421cca92b11_thumbnail_600x.jpg"
                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                            "PINK":  [
                                                                                                                                                                                                                                         "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/PINK/17657883688b0c6eb4c2006aa6bdd8c154f3b7524e_thumbnail_600x.jpg",
                                                                                                                                                                                                                                         "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/PINK/176707713934fef3ea481ebecb7cdfe95cb9fc8a7f_thumbnail_600x.jpg",
                                                                                                                                                                                                                                         "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/PINK/1767077145c1a2ae07f8d0515178a4720b911b2b8f_thumbnail_600x.jpg",
                                                                                                                                                                                                                                         "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/PINK/1767077148a4e1a1e2938d89d6f05ddf797b036575_thumbnail_600x.jpg",
                                                                                                                                                                                                                                         "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/PINK/17670771518c6c650ba97e24d21aea348153b228fa_thumbnail_600x.jpg",
                                                                                                                                                                                                                                         "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/PINK/17756153240b2139a46c02de9f89dd916cfbaff147_thumbnail_600x.jpg"
                                                                                                                                                                                                                                     ],
                                                                                                                                                                                                                            "BLACK":  [
                                                                                                                                                                                                                                          "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/BLACK/1749092202370a3138523fb21387aa45fc44fe91c2_thumbnail_600x.jpg",
                                                                                                                                                                                                                                          "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/BLACK/174909220240263c5bc44f3cf2bf0cd1b1e5388358_thumbnail_600x.jpg",
                                                                                                                                                                                                                                          "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/BLACK/1749092202543008ffe0cd7eee8b33b1db85fd2ed4_thumbnail_600x.jpg",
                                                                                                                                                                                                                                          "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/BLACK/1749092202b7a0a10b41e24e9a307a9ce76485df1f_thumbnail_600x.jpg",
                                                                                                                                                                                                                                          "/3pcs Women\u0027s Sexy Lingerie Set Front Hook 34 Cup Bra With Adjustable Straps And Metal Chain Decor, Adjustable Garter Belt, And Sexy Thong. Lace Accents, Comfortable Lingerie Set Suitable For Elegant Occ/BLACK/1749092202bbc5aae28e4a180a91710845743b4aaf_thumbnail_600x.jpg"
                                                                                                                                                                                                                                      ]
                                                                                                                                                                                                                        },
    "Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring":  {
                                                                                                                "brown":  [
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/brown/17586161073751e45e61ecaf5a3a392c1bc2a3924a_thumbnail_600x.jpg",
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/brown/1758616110fc38dca002e282e624dda66573302785_thumbnail_600x.jpg"
                                                                                                                          ],
                                                                                                                "black":  [
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/black/174408129146654656e74be917ca457b3eebbb0aec_thumbnail_600x.jpg",
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/black/17440812920cda10f6086d5e499afefdfe92b977d0_thumbnail_600x.jpg",
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/black/1744081292c2bd87f6e640a76ef734f61a4b960030_thumbnail_600x.jpg",
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/black/1744081308e1399d00137575dfd5561a784d51aaed_thumbnail_600x.jpg"
                                                                                                                          ],
                                                                                                                "GReen":  [
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/GReen/17568892932f218cbd52ff76c1c1fb75c7e1b01a49_thumbnail_600x.jpg",
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/GReen/17568892941c28ad8c1d15921aac763d1fd5aa6916_thumbnail_600x.jpg",
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/GReen/1756889294fc7b1d5c2a13ec276df671fe20447c9d_thumbnail_600x.jpg"
                                                                                                                          ],
                                                                                                                "pink":  [
                                                                                                                             "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/pink/1750056711099dee924923ee7a245bda1f4d7eb1f2_thumbnail_600x.jpg",
                                                                                                                             "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/pink/17500567114d1e0db1d56dfdf25f945b666bccada6_thumbnail_600x (1).jpg",
                                                                                                                             "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/pink/17500567114d1e0db1d56dfdf25f945b666bccada6_thumbnail_600x.jpg",
                                                                                                                             "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/pink/1750056711712cb7135c49c3523d122914d5678dc8_thumbnail_600x.jpg"
                                                                                                                         ],
                                                                                                                "grey":  [
                                                                                                                             "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/grey/17501240813057c1bf4c2e51b3001dd0254e0d12d8_thumbnail_600x.jpg",
                                                                                                                             "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/grey/1750124081348a4e3526966f9947be6c7a4858570e_thumbnail_600x.jpg",
                                                                                                                             "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/grey/1750124081d02a98408742c3ebc9c0947dc1f89770_thumbnail_600x.jpg",
                                                                                                                             "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/grey/1750124081e52f4ff72bfade82b266dc70da782170_thumbnail_600x.jpg"
                                                                                                                         ],
                                                                                                                "white":  [
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/white/1750056671605e7ae40520332578afe20b8b57ef64_thumbnail_600x.jpg",
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/white/17500566718b92d6a3a9d4c340db02dbfd46b0571d_thumbnail_600x.jpg",
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/white/175005667198c098297fd3571c69f6fe70364e538f_thumbnail_600x.jpg",
                                                                                                                              "/Women\u0027s High Waist Solid Color Flare Yoga Leggings, Workout Running Fitness Pants Black Spring/white/1750056671c2f76c7351257f4f0e170d391bd3671f_thumbnail_600x.jpg"
                                                                                                                          ]
                                                                                                            },
    "SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear":  {
                                                                                                                                           "WHITE":  [
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/WHITE/1701827564652c3de2e065d38ee8b3c9b89d664997_thumbnail_600x.jpg",
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/WHITE/1701827568c23bb790f83872d730fe522f85ca4648_thumbnail_600x.jpg",
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/WHITE/1701827576d6cc316529bff71b85237c0b2405ec8f_thumbnail_600x.jpg",
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/WHITE/1701827582ef7344218c32fec0f1603a6246cc8710_thumbnail_600x.jpg",
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/WHITE/1701827587ee083da4ab723ef21f8958276b8b5d14_thumbnail_600x.jpg",
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/WHITE/1701827596663dbca9414f5f517d8d4367e7161918_thumbnail_600x.jpg"
                                                                                                                                                     ],
                                                                                                                                           "BLACK":  [
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/BLACK/170548244174619fb6b70dd4cabf6561ab0a7fca7a_thumbnail_600x.jpg",
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/BLACK/17054824448a5b7c06efb46a705b2894f68076bc34_thumbnail_600x.jpg",
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/BLACK/17054824460fb73c22879e0dba787ca33427f8acfb_thumbnail_600x.jpg",
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/BLACK/1705482453a3929b55632678c274242039990b55c5_thumbnail_600x.jpg",
                                                                                                                                                         "/SXY Commute Minimalist Office Old Money Simple Women\u0027s Striped Hollow Out Patchwork Skinny Leggings, Everyday Casual Wear/BLACK/17159413019a5f999814590e826867bd3e7cf59b23_thumbnail_600x.jpg"
                                                                                                                                                     ]
                                                                                                                                       },
    "2 PCs undercover seductive wear":  {
                                            "red":  [
                                                        "/2 PCs undercover seductive wear/red/1725587148174885e83039444a93eef2258c538f08_thumbnail_600x (1).jpg",
                                                        "/2 PCs undercover seductive wear/red/1725587148174885e83039444a93eef2258c538f08_thumbnail_600x.jpg",
                                                        "/2 PCs undercover seductive wear/red/17255871512e1e60d9acaef440f53ea19aaac8d6af_thumbnail_600x.jpg",
                                                        "/2 PCs undercover seductive wear/red/17255871552a8ab98234b11ffcf4a04b0fb9cd8477_thumbnail_600x.jpg",
                                                        "/2 PCs undercover seductive wear/red/172558715898b7a3303ed3c9a34a2adbc34537670d_thumbnail_600x.jpg",
                                                        "/2 PCs undercover seductive wear/red/172558716264319151d3f0de8c8e6483f0653e3aeb_thumbnail_600x.jpg"
                                                    ],
                                            "black":  [
                                                          "/2 PCs undercover seductive wear/black/1670032236228213049aa2af646d63c3bea1ce12a8_thumbnail_600x.jpg",
                                                          "/2 PCs undercover seductive wear/black/1670032238d62f76de78f0b542c22490512db6b949_thumbnail_600x.jpg",
                                                          "/2 PCs undercover seductive wear/black/167003224042617fa1ebaffd906f1068c99f382c80_thumbnail_600x.jpg",
                                                          "/2 PCs undercover seductive wear/black/16700322425ada3643ce83e588ba354d754193239a_thumbnail_600x.jpg",
                                                          "/2 PCs undercover seductive wear/black/16700322463ff8829e5821b849e67c7441f6f64dba_thumbnail_600x.jpg",
                                                          "/2 PCs undercover seductive wear/black/1718095995106a76cc3a02e3c5fadb31a8354b621b_thumbnail_600x.jpg"
                                                      ]
                                        }
} as const;

